
# Site settings

url: "http://BelhalK.github.io"
baseurl: ""
google-tracking-id: "111"

#############
# HTML Head #
#############

author: "Belhal Karimi"
lang: "en"
title: "Belhal Karimi"
favicon: "/img/ico.ico"
description: "Personal website of Belhal Karimi."
keywords: "belhal, karimi, supelec, mit"

################
# Intro layout #
################

# black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/SF.jpg"
me-img: "/img/my_picture3.jpg"

##############################
# Dynamic Text on the header #
##############################

# dynamic-typing: True
# shuffle: True	# Shuffle the lines.
# loop: True
# loop-count:	False # Set False for infinite loop, or set any number for finite loop.
# type-speed:	10		# Default 10
# start-delay: 200	# Default 200
# delete-delay: 5000	# Default 5000
# lines:			# You can add HTML Tags in the Text
#   - text: "The lower you fall, the higher you'll fly."
#   - text: "Where’s your will to be weird?"

########
# Blog #
########

post-preview-words: 128

paginate: 10

fb-share: False
twitter-share: False
reddit-share: False
disqus-shortname: False

###############
# Life Events #
###############

events:
  - image: ""
    date: "2016
    description: "What's Next?"
  - image: "/img/career/gates.png"
    date: "Feb. 2016 - April 2016"
    description: "Data Scientist at Gates Foundation"
  # - image: "/img/career/spidertocat.png"
  #   date: "July 2014 - Aug. 2014"
  #   description: "ST Microelectronics India - Summer Internship"
  - image: "/img/career/mit2.jpg"
    date: "2015 - 2016"
    description: "MIT - Visiting Student in Machine Learning"
  - image: "/img/career/CS.jpg"
    date: "Sept. 2011 - Aug. 2015"
    description: "Supelec - Diplome d'Ingenieur (MS) in Computer Science and Applied Mathematics"
  - image: "/img/career/hoche2.png"
    date: "Sept. 2009 - June 2011"
    description: "Lycee Hoche - Classes Preparatoires"

# # First image of the Career timeline
# career-img: "/img/career/eiffel2.png"

##################
# Contact layout #
##################

email: "belhal.karimi@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/BelhalK"
  # - title: "youtube"
  #   url: "http://youtube.com/"
  - title: "linkedin"
    url: "https://linkedin.com/in/belhal"
  #  url: "https://www.linkedin.com/in/sebdubois"
  - title: "github"
    url: "https://github.com/BelhalK"
  - title: "envelope"
  #  url: "https://github.com/sds-dubois"
  # - title: "rss"
  #   url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Resume: 'resume'
  Projects: 'projects'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
